"""
Generator for the SYNTHETIC seed history shipped with this starter repo.

READ THIS BEFORE YOU TRUST data/historik_elpris.csv OR data/historik_vader.csv
==============================================================================
The two CSV files in this folder are NOT real measurements. They were
generated by this script so that `model/train.py` runs end to end on a fresh
clone, before anyone has talked to an API.

They are shaped to match the real sources exactly -- same column names, same
separators, same timestamp conventions, same resolution change, same kinds of
holes -- so code written against them keeps working when you swap in real
data. But the numbers themselves are invented.

To replace them with the real thing, run:

    uv run python data/fetch_historik.py --from 2024-08-01 --to 2026-08-20

which downloads from elprisetjustnu.se and SMHI and overwrites both CSVs.
Do that before you draw any conclusion about Swedish electricity prices.

What is deliberately modelled here
----------------------------------
Everything in this list is also true of the real data. None of it is a bug.

1.  RESOLUTION CHANGE. Sweden moved from hourly to 15-minute electricity
    prices on 2025-10-01. Before that date each day has 24 price points;
    from that date it has 96. Any code that assumes "24 rows per day"
    silently breaks on data spanning the boundary.

2.  TWO TIMEZONE CONVENTIONS. Prices carry local Swedish time with an
    explicit UTC offset (+01:00 winter, +02:00 summer). SMHI observations
    are in UTC with no offset marker at all. Joining them naively is off by
    one or two hours depending on the season.

3.  DST DAYS. The last Sunday in March has 23 hours, the last Sunday in
    October has 25. Grouping by date and dividing by 24 is wrong twice a year.

4.  MISSING WEATHER HOURS. Real SMHI series drop individual hours when a
    sensor was down. Gaps here are mostly single hours, with a few multi-day
    outages.

5.  QUALITY CODES. SMHI marks each value G (checked and approved) or Y
    (suspect or aggregated). Y values are not wrong exactly, but they are
    not the same thing as G values either.

6.  NEGATIVE AND SPIKED PRICES. Sunny low-demand summer hours in SE3/SE4 can
    go below zero. Cold winter evenings can spike an order of magnitude above
    normal. Both are real, and both wreck a model that clips or drops them
    without thinking.

7.  A FEW DUPLICATE ROWS. Re-ingestion happens. The price files contain a
    small number of exact duplicate rows.

Author: course starter material, YH-02032.
"""

from __future__ import annotations

import argparse
import zoneinfo
from datetime import date, datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

STOCKHOLM = zoneinfo.ZoneInfo("Europe/Stockholm")
UTC = zoneinfo.ZoneInfo("UTC")

# The date Sweden switched from hourly to quarter-hourly electricity prices.
QUARTER_HOUR_FROM = date(2025, 10, 1)

# Price areas and the weather station each one is paired with.
#
# NOTE FOR THE COURSE INSTRUCTOR: only station 98230 has been verified against
# the live SMHI API. The other three ids are placeholders. Run
#   uv run python data/fetch_historik.py --find-station "Lulea"
# to look up the real key before handing the team assignment sheet out.
AREAS = {
    "SE1": {
        "station_id": 162860,
        "station_name": "Lulea-Kallax Flygplats",   # TODO verify id
        "base_price": 0.32,
        "temp_mean": 2.0,
        "temp_amp": 13.0,
    },
    "SE2": {
        "station_id": 134110,
        "station_name": "Ostersunds Flygplats",
        "base_price": 0.36,
        "temp_mean": 3.5,
        "temp_amp": 12.0,
    },
    "SE3": {
        "station_id": 98230,
        "station_name": "Stockholm-Observatoriekullen A",   # verified
        "base_price": 0.62,
        "temp_mean": 7.5,
        "temp_amp": 10.5,
    },
    "SE4": {
        "station_id": 53430,
        "station_name": "Malmo A",                  # TODO verify id
        "base_price": 0.78,
        "temp_mean": 9.0,
        "temp_amp": 9.5,
    },
}


def _daily_temperature_curve(
    rng: np.random.Generator,
    day: date,
    cfg: dict,
    carry: float,
) -> tuple[np.ndarray, float]:
    """24 hourly temperatures for one day, with weather that persists a bit.

    `carry` is a slow-moving anomaly passed from the previous day so that cold
    snaps last several days instead of resampling independently every morning.
    """
    day_of_year = day.timetuple().tm_yday
    # Seasonal baseline, coldest in mid-January.
    seasonal = cfg["temp_mean"] - cfg["temp_amp"] * np.cos(
        2 * np.pi * (day_of_year - 15) / 365.25
    )
    carry = 0.82 * carry + rng.normal(0.0, 2.4)
    hours = np.arange(24)
    # Diurnal swing: coldest around 04, warmest around 15. Bigger swing in summer.
    swing = 3.0 + 2.5 * np.sin(2 * np.pi * (day_of_year - 100) / 365.25)
    diurnal = swing * np.sin(2 * np.pi * (hours - 9) / 24)
    noise = rng.normal(0.0, 0.7, size=24)
    return seasonal + carry + diurnal + noise, carry


def _wind_series(rng: np.random.Generator, n: int, carry: float) -> tuple[np.ndarray, float]:
    """Hourly wind speed, also autocorrelated -- windy days come in runs."""
    out = np.empty(n)
    for i in range(n):
        carry = 0.9 * carry + rng.normal(0.0, 1.1)
        out[i] = max(0.2, 4.5 + carry)
    return out, carry


def _price_from_drivers(
    rng: np.random.Generator,
    stamps: pd.DatetimeIndex,
    temps: np.ndarray,
    winds: np.ndarray,
    cfg: dict,
    area: str,
) -> np.ndarray:
    """Turn temperature and wind into a plausible price curve.

    The relationship is real in direction if not in magnitude: cold pushes
    prices up (heating demand), wind pushes them down (cheap supply), and
    demand has a twin-peaked daily shape.
    """
    hours = stamps.hour.to_numpy() + stamps.minute.to_numpy() / 60.0
    day_of_year = stamps.dayofyear.to_numpy()
    weekday = stamps.dayofweek.to_numpy()

    # Twin daily peaks: morning ~08, evening ~18.
    morning = np.exp(-0.5 * ((hours - 8.0) / 2.0) ** 2)
    evening = np.exp(-0.5 * ((hours - 18.0) / 2.4) ** 2)
    shape = 0.55 + 0.75 * morning + 0.95 * evening

    # Weekends are cheaper -- less industry.
    shape = shape * np.where(weekday >= 5, 0.82, 1.0)

    # Winter is expensive. Peaks in mid-January, same phase as the coldest
    # part of the temperature curve in _daily_temperature_curve.
    seasonal = 1.0 + 0.55 * np.cos(2 * np.pi * (day_of_year - 15) / 365.25)

    # Cold drives price up, hard below freezing.
    cold = np.clip(5.0 - temps, 0, None) / 10.0
    heating = 1.0 + 0.42 * cold + 0.10 * np.clip(-temps, 0, None) / 5.0

    # Wind drives price down.
    wind_relief = np.clip(1.0 - 0.055 * (winds - 4.5), 0.35, 1.5)

    level = cfg["base_price"] * shape * seasonal * heating * wind_relief

    # Multiplicative noise, plus a slow drift so the series is not stationary.
    level = level * np.exp(rng.normal(0.0, 0.22, size=len(stamps)))

    # Occasional scarcity spikes, concentrated in cold winter evenings.
    spike_risk = 0.0016 * (1.0 + 4.0 * cold) * (1.0 + 2.0 * evening)
    spikes = rng.random(len(stamps)) < spike_risk
    level = np.where(spikes, level * rng.uniform(4.0, 14.0, size=len(stamps)), level)

    # Negative prices: sunny, mild, low-demand midday hours in the south.
    if area in ("SE3", "SE4"):
        summer = (day_of_year > 110) & (day_of_year < 240)
        midday = (hours > 10) & (hours < 15)
        cheap_risk = summer & midday & (winds > 6.0)
        flip = cheap_risk & (rng.random(len(stamps)) < 0.10)
        level = np.where(flip, rng.uniform(-0.35, 0.02, size=len(stamps)), level)

    return np.round(level, 5)


def build(start: date, end: date, seed: int = 20260825) -> tuple[pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(seed)

    price_rows: list[dict] = []
    weather_rows: list[dict] = []

    for area, cfg in AREAS.items():
        temp_carry = 0.0
        wind_carry = 0.0
        day = start
        while day <= end:
            hourly_temp, temp_carry = _daily_temperature_curve(rng, day, cfg, temp_carry)
            hourly_wind, wind_carry = _wind_series(rng, 24, wind_carry)

            # ---- weather: hourly, UTC, exactly as SMHI serves it -------------
            # Local midnight is not UTC midnight, and the offset changes twice
            # a year. Build the day in local time, then convert.
            for hour in range(24):
                try:
                    local_dt = datetime(day.year, day.month, day.day, hour, tzinfo=STOCKHOLM)
                except ValueError:
                    continue
                utc_dt = local_dt.astimezone(UTC)
                weather_rows.append(
                    {
                        "_area": area,
                        "Datum": utc_dt.strftime("%Y-%m-%d"),
                        "Tid (UTC)": utc_dt.strftime("%H:%M:%S"),
                        "Lufttemperatur": round(float(hourly_temp[hour]), 1),
                        "Vindhastighet": round(float(hourly_wind[hour]), 1),
                        # SMHI marks roughly a fifth of archive values as suspect.
                        "Kvalitet": "Y" if rng.random() < 0.22 else "G",
                        "Stationsnummer": cfg["station_id"],
                        "Stationsnamn": cfg["station_name"],
                    }
                )

            # ---- prices: local time with offset, 24 or 96 points -------------
            quarter = day >= QUARTER_HOUR_FROM
            step = timedelta(minutes=15) if quarter else timedelta(hours=1)

            # Walk real local wall-clock time so DST days come out 23/25 hours
            # long by construction rather than by special-casing.
            cursor = datetime(day.year, day.month, day.day, tzinfo=STOCKHOLM)
            day_end = datetime(day.year, day.month, day.day, tzinfo=STOCKHOLM) + timedelta(days=1)
            stamps: list[datetime] = []
            while cursor < day_end:
                stamps.append(cursor)
                cursor = (cursor.astimezone(UTC) + step).astimezone(STOCKHOLM)

            idx = pd.DatetimeIndex([s.replace(tzinfo=None) for s in stamps])
            temps_at = np.interp(
                idx.hour.to_numpy() + idx.minute.to_numpy() / 60.0,
                np.arange(24),
                hourly_temp,
            )
            winds_at = np.interp(
                idx.hour.to_numpy() + idx.minute.to_numpy() / 60.0,
                np.arange(24),
                hourly_wind,
            )
            sek = _price_from_drivers(rng, idx, temps_at, winds_at, cfg, area)
            exr = round(float(rng.normal(11.2, 0.35)), 6)

            for s, value in zip(stamps, sek, strict=True):
                end_stamp = (s.astimezone(UTC) + step).astimezone(STOCKHOLM)
                price_rows.append(
                    {
                        "price_area": area,
                        "SEK_per_kWh": float(value),
                        "EUR_per_kWh": round(float(value) / exr, 5),
                        "EXR": exr,
                        "time_start": s.isoformat(),
                        "time_end": end_stamp.isoformat(),
                    }
                )

            day += timedelta(days=1)

    prices = pd.DataFrame(price_rows)
    weather = pd.DataFrame(weather_rows)

    # ---- now damage it, the way reality damages it ------------------------
    weather = _punch_holes_in_weather(weather, rng)
    prices = _duplicate_a_few_rows(prices, rng)

    return prices, weather


def _punch_holes_in_weather(weather: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    """Drop hours the way a real sensor drops them."""
    keep = np.ones(len(weather), dtype=bool)

    # Scattered single-hour dropouts.
    keep &= rng.random(len(weather)) > 0.018

    # A handful of multi-day outages per station.
    for area in weather["_area"].unique():
        idx = np.flatnonzero(weather["_area"].to_numpy() == area)
        for _ in range(3):
            if len(idx) < 400:
                continue
            start = int(rng.integers(0, len(idx) - 300))
            length = int(rng.integers(30, 260))
            keep[idx[start : start + length]] = False

    return weather.loc[keep].reset_index(drop=True)


def _duplicate_a_few_rows(prices: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    """Re-ingestion leaves exact duplicates behind. Roughly 0.1% here."""
    n_dupes = max(1, int(0.001 * len(prices)))
    picks = rng.integers(0, len(prices), size=n_dupes)
    out = pd.concat([prices, prices.iloc[picks]], ignore_index=True)
    return out.sort_values(["price_area", "time_start"], kind="stable").reset_index(drop=True)


def write_smhi_style_csv(weather: pd.DataFrame, path: Path) -> None:
    """Write one combined file that keeps SMHI's semicolon/UTC conventions.

    The real API gives you one file per station. This ships all four in one
    file with a `Stationsnummer` column so the starter repo stays a single
    download; `fetch_historik.py` produces the same shape from four calls.
    """
    cols = [
        "Stationsnummer",
        "Stationsnamn",
        "Datum",
        "Tid (UTC)",
        "Lufttemperatur",
        "Vindhastighet",
        "Kvalitet",
    ]
    weather[cols].to_csv(path, sep=";", index=False, encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--from", dest="start", default="2024-08-01")
    ap.add_argument("--to", dest="end", default="2026-08-20")
    ap.add_argument("--outdir", default=str(Path(__file__).parent))
    args = ap.parse_args()

    start = date.fromisoformat(args.start)
    end = date.fromisoformat(args.end)
    outdir = Path(args.outdir)

    prices, weather = build(start, end)

    price_path = outdir / "historik_elpris.csv.gz"
    weather_path = outdir / "historik_vader.csv.gz"

    prices.to_csv(price_path, index=False, compression="gzip")
    # gzip through pandas keeps the semicolon convention intact
    write_smhi_style_csv(weather, weather_path)

    print(f"prices  {len(prices):>8,} rows -> {price_path}")
    print(f"weather {len(weather):>8,} rows -> {weather_path}")
    print()
    print("Reminder: this is synthetic. Run fetch_historik.py for real data.")


if __name__ == "__main__":
    main()
