[project]
name = "ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JulianHx", email = "152697535+JulianHoxha@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.6",
    "psycopg2-binary==2.9.10",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "uvicorn==0.34.0",
]

[project.scripts]
ingestion = "ingestion:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
